name: Run the unit tests
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/install-dependencies.yml

      - name: Run pytest
        run: pytest

  runmigrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/install-dependencies.yml

      - name: Run djago migrate
        run: python manage.py migrate


  migration-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: ./.github/actions/install-dependencies.yml

      - name: Run runmigrations
        run: python manage.py makemigrations --check
        
  build-docker-image:
    runs-on: ubuntu-latest
    needs: 
      - test
      - runmigrations
      - migration-check
    if: github.ref == 'refs/heads/main'
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GMCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-actions@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: build and push
        uses: docker/build-push-actions@v6
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}